<div style="text-align: center;background-color: gold; padding: 25px; border-radius: 5px; margin-bottom: 10px;">
    <h2> AUTHORSHIP ATTRIBUTION USING SENTENCE LENGTH AND PUNCTUATION PATTERN </h2>
</div>

* Main Idea : `Harun Or Rashid Sir` 😊✨
* Coding    : `Tanbeer Jubaer` 🌟 and `Minhazul Islam` 🏆
<!-- 😊
✨
🌟
👍
❤️
🎉
🌸
🚀
🌈
🎈
🎂
📚
🎵
🎲
🏆
🎥
🍕
🍎
🚗
⏰ -->

<div style="text-align: center;">
    <h2> 1. Import Necessary Libraries</h2>
</div>

In [1]:
# Regular EDA(exploratory data analysis) and plotting libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
%matplotlib inline

from tqdm import tqdm
import string
import statistics
import re
import joblib
import random
import statistics
from collections import Counter
from scipy import stats
import os
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics.pairwise import cosine_similarity
import zipfile
from matplotlib.lines import Line2D

In [2]:
data = pd.read_excel('/kaggle/input/author-data/author_data.xlsx')
data.head(2)

book_id        writer  st_state5x3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray       0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray       0.261259   

   st_state5x3_2  st_state5x3_3  st_state5x3_4  st_state5x3_5  state5x5_1  \
0       0.253602       0.207741       0.138053       0.182240    0.332685   
1       0.261148       0.217963       0.113027       0.146602    0.340206   

   state5x5_2  state5x5_3  ...  state7x7_47  state7x7_48  state7x7_49  \
0    0.282101    0.177043  ...     0.108696     0.072464     0.094203   
1    0.283505    0.185567  ...     0.147059     0.058824     0.147059   

       mean  median  mode   variance   std_dev  \
0  8.076395     7.0     5  31.971834  5.654364   
1  7.318498     6.0     3  27.927666  5.284663   

                                      punc_state_mat          punc_st_state  
0  [[0.52 0.13 0.03 0.32]\n [0.52 0.11 0.03 0.34]...  [0.56 0.11 0.04 0.29]  
1  [[0.53 0.14 0.03 0.31]\n [0.64 0.07 0.06 0.23]...  [0.55 0.12 0.04 0.29]  

[2 rows x 175 columns]

In [3]:
data.shape

(90, 175)

In [4]:
data.dtypes

book_id            object
writer             object
st_state5x3_1     float64
st_state5x3_2     float64
st_state5x3_3     float64
                   ...   
mode                int64
variance          float64
std_dev           float64
punc_state_mat     object
punc_st_state      object
Length: 175, dtype: object

In [5]:
books = data['book_id']
books

0                  feluda_33_Noyon_Rahashya
1     feluda_22_OmborSen_Ontordhan_Rahashya
2                feluda_13_Bombayer_Bombete
3             feluda_12_Ghurghutiar_Ghotona
4           feluda_19_JotoKando_Kathmandute
                      ...                  
85                    MisirAli-2-Nishithini
86                 MisirAli-11-AmiyMisirAli
87                    MisirAli-5-Brihonnola
88             MisirAli-21-SabhdhanMisirAli
89                        MisirAli-8-Oneesh
Name: book_id, Length: 90, dtype: object

In [6]:
data.writer.value_counts()

writer
Humayun Ahmed    42
Satyajit Ray     35
Rabindranath     13
Name: count, dtype: int64

In [7]:
def writer_label(name):
    if name == 'Humayun Ahmed':
        return 0
    elif name == 'Satyajit Ray':
        return 1
    elif name == 'Rabindranath':
        return 2

In [8]:
from sklearn.preprocessing import LabelEncoder
# Initialize LabelEncoder
label_encoder = LabelEncoder()
# data['en_writer'] = label_encoder.fit_transform(data['writer'])

In [9]:
data['en_writer'] = data['writer'].apply(writer_label)

In [10]:
data.head(2)

book_id        writer  st_state5x3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray       0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray       0.261259   

   st_state5x3_2  st_state5x3_3  st_state5x3_4  st_state5x3_5  state5x5_1  \
0       0.253602       0.207741       0.138053       0.182240    0.332685   
1       0.261148       0.217963       0.113027       0.146602    0.340206   

   state5x5_2  state5x5_3  ...  state7x7_48  state7x7_49      mean  median  \
0    0.282101    0.177043  ...     0.072464     0.094203  8.076395     7.0   
1    0.283505    0.185567  ...     0.058824     0.147059  7.318498     6.0   

   mode   variance   std_dev  \
0     5  31.971834  5.654364   
1     3  27.927666  5.284663   

                                      punc_state_mat          punc_st_state  \
0  [[0.52 0.13 0.03 0.32]\n [0.52 0.11 0.03 0.34]...  [0.56 0.11 0.04 0.29]   
1  [[0.53 0.14 0.03 0.31]\n [0.64 0.07 0.06 0.23]...  [0.55 0.12 0.04 0.29]   

   en_writer  
0          1  
1          1  

[2 rows x 176 columns]

In [11]:
data['en_writer'].value_counts()

en_writer
0    42
1    35
2    13
Name: count, dtype: int64

In [12]:
data.iloc[40]

book_id                                     ProjapotirNirbondho1908
writer                                                 Rabindranath
st_state5x3_1                                              0.368354
st_state5x3_2                                              0.184394
st_state5x3_3                                              0.149378
                                        ...                        
variance                                                  52.261834
std_dev                                                    7.229235
punc_state_mat    [[0.52 0.07 0.05 0.35]\n [0.68 0.11 0.04 0.17]...
punc_st_state                                 [0.53 0.09 0.07 0.31]
en_writer                                                         2
Name: 40, Length: 176, dtype: object

In [13]:
# Drop row at position 40
data = data.drop(data.index[40])

In [14]:
data.iloc[40]

book_id                                               Maloncho-1934
writer                                                 Rabindranath
st_state5x3_1                                              0.137564
st_state5x3_2                                              0.281439
st_state5x3_3                                              0.227536
                                        ...                        
variance                                                  28.882469
std_dev                                                    5.374241
punc_state_mat    [[0.53 0.03 0.02 0.42]\n [0.58 0.02 0.01 0.39]...
punc_st_state                                 [0.56 0.03 0.02 0.39]
en_writer                                                         2
Name: 41, Length: 176, dtype: object

In [15]:
data['en_writer'].value_counts()

en_writer
0    42
1    35
2    12
Name: count, dtype: int64

In [16]:
x = 75
sc = data.columns[x:x+38]
sc

Index(['st_state6x3_6', 'state6x6_1', 'state6x6_2', 'state6x6_3', 'state6x6_4',
       'state6x6_5', 'state6x6_6', 'state6x6_7', 'state6x6_8', 'state6x6_9',
       'state6x6_10', 'state6x6_11', 'state6x6_12', 'state6x6_13',
       'state6x6_14', 'state6x6_15', 'state6x6_16', 'state6x6_17',
       'state6x6_18', 'state6x6_19', 'state6x6_20', 'state6x6_21',
       'state6x6_22', 'state6x6_23', 'state6x6_24', 'state6x6_25',
       'state6x6_26', 'state6x6_27', 'state6x6_28', 'state6x6_29',
       'state6x6_30', 'state6x6_31', 'state6x6_32', 'state6x6_33',
       'state6x6_34', 'state6x6_35', 'state6x6_36', 'st_state7x3_1'],
      dtype='object')

In [17]:
# X = data.drop(['book_id', 'writer', 'punc_state_mat', 'punc_st_state'], axis=1)
X = data[sc]
# X = data[['mean', 'median', 'mode', 'variance', 'std_dev']]
y = data[['book_id', 'writer', 'en_writer']]

In [18]:
X.head(2)

st_state6x3_6  state6x6_1  state6x6_2  state6x6_3  state6x6_4  state6x6_5  \
0       0.107831    0.332039    0.281553    0.176699    0.091262    0.050485   
1       0.084808    0.338462    0.282051    0.184615    0.092308    0.056410   

   state6x6_6  state6x6_7  state6x6_8  state6x6_9  ...  state6x6_28  \
0    0.067961    0.209030    0.274247    0.219064  ...     0.165746   
1    0.046154    0.302564    0.230769    0.220513  ...     0.153846   

   state6x6_29  state6x6_30  state6x6_31  state6x6_32  state6x6_33  \
0     0.077348     0.082873     0.185039     0.188976     0.208661   
1     0.115385     0.076923     0.123077     0.184615     0.323077   

   state6x6_34  state6x6_35  state6x6_36  st_state7x3_1  
0     0.145669     0.102362     0.169291       0.217005  
1     0.107692     0.123077     0.138462       0.255764  

[2 rows x 38 columns]

In [19]:
y.head(2)

book_id        writer  en_writer
0               feluda_33_Noyon_Rahashya  Satyajit Ray          1
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          1

In [20]:
# Split the data into training and testing sets
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
len(X_train), len(X_test)

(71, 18)

In [21]:
y_train.en_writer.value_counts(), y_test.en_writer.value_counts()

(en_writer
 0    35
 1    27
 2     9
 Name: count, dtype: int64,
 en_writer
 1    8
 0    7
 2    3
 Name: count, dtype: int64)

In [22]:
y_train.head()

book_id         writer  en_writer
86         MisirAli-11-AmiyMisirAli  Humayun Ahmed          0
35                     JogaJog-1929   Rabindranath          2
26         feluda_31_Londone_Feluda   Satyajit Ray          1
48  EkjonHimuoKoektiJijhipoka(1999)  Humayun Ahmed          0
31         feluda_7_Baksho_Rahashya   Satyajit Ray          1

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)

# Train the model
rf_classifier.fit(X_train, y_train.en_writer)

RandomForestClassifier(random_state=42)

In [24]:
# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test.en_writer, y_pred)
report = classification_report(y_test.en_writer, y_pred)

In [25]:
print(list(y_test.en_writer))
print(list(y_pred))

[2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 0]
[2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0]


In [26]:
print(f'Accuracy = {accuracy*100}%')
print(report)

Accuracy = 94.44444444444444%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.89      1.00      0.94         8
           2       1.00      0.67      0.80         3

    accuracy                           0.94        18
   macro avg       0.96      0.89      0.91        18
weighted avg       0.95      0.94      0.94        18



In [27]:
y_test['prediction'] = rf_classifier.predict(X_test)

In [28]:
y_test

book_id         writer  en_writer  prediction
45              BouThakuranirHath-1883   Rabindranath          2           2
54                    Ebong_himu(1995)  Humayun Ahmed          0           0
30  feluda_3_Koilash_Chowdhurir_pathor   Satyajit Ray          1           1
12         feluda_1_Feludar_Goendagiri   Satyajit Ray          1           1
50              HimurDitioProhor(1997)  Humayun Ahmed          0           0
0             feluda_33_Noyon_Rahashya   Satyajit Ray          1           1
65                          Himu(1993)  Humayun Ahmed          0           0
18          feluda_34_Robertsoner_Rubi   Satyajit Ray          1           1
10        feluda_27_Vushorgo_Bhoyonkor   Satyajit Ray          1           1
22     feluda_10_Royal_Bengal_Rahashya   Satyajit Ray          1           1
4      feluda_19_JotoKando_Kathmandute   Satyajit Ray          1           1
33                feluda_17_Hottyapuri   Satyajit Ray          1           1
43                      CharOddhay1934   Rabindranath          2           1
81                     MisirAli-6-Bhoy  Humayun Ahmed          0           0
82         MisirAli-14-MisirAlirChosma  Humayun Ahmed          0           0
39                     ChokherBali1903   Rabindranath          2           2
78                     MisirAli-1-Debi  Humayun Ahmed          0           0
62              HimurModdhodupur(2009)  Humayun Ahmed          0           0

In [29]:
x = 75
sc = data.columns[x:x+38]
sc

Index(['st_state6x3_6', 'state6x6_1', 'state6x6_2', 'state6x6_3', 'state6x6_4',
       'state6x6_5', 'state6x6_6', 'state6x6_7', 'state6x6_8', 'state6x6_9',
       'state6x6_10', 'state6x6_11', 'state6x6_12', 'state6x6_13',
       'state6x6_14', 'state6x6_15', 'state6x6_16', 'state6x6_17',
       'state6x6_18', 'state6x6_19', 'state6x6_20', 'state6x6_21',
       'state6x6_22', 'state6x6_23', 'state6x6_24', 'state6x6_25',
       'state6x6_26', 'state6x6_27', 'state6x6_28', 'state6x6_29',
       'state6x6_30', 'state6x6_31', 'state6x6_32', 'state6x6_33',
       'state6x6_34', 'state6x6_35', 'state6x6_36', 'st_state7x3_1'],
      dtype='object')

In [30]:
# X = data.drop(['book_id', 'writer', 'punc_state_mat', 'punc_st_state'], axis=1)
X = data[sc]
# X = data[['mean', 'median', 'mode', 'variance', 'std_dev']]
y = data[['book_id', 'writer', 'en_writer']]

In [31]:
from sklearn.model_selection import cross_val_score

# Perform cross-validation and get scores

model = RandomForestClassifier(n_estimators=100)
scores = cross_val_score(model, X, y.en_writer, cv=5)
print("Cross-Validation Scores:", scores)


print("Mean Score:", scores.mean())
print("Standard Deviation:", scores.std())

Cross-Validation Scores: [1.         0.94444444 0.94444444 1.         0.94117647]
Mean Score: 0.9660130718954247
Standard Deviation: 0.02777585537369384


In [32]:
for i in range(1, 10):
    model = RandomForestClassifier(n_estimators=100, random_state = i)
    scores = cross_val_score(model, X, y.en_writer, cv=4)
    print("Mean Score:", scores.mean())


Mean Score: 0.9545454545454546
Mean Score: 0.9659090909090909
Mean Score: 0.9550395256916996
Mean Score: 0.9659090909090909
Mean Score: 0.9659090909090909
Mean Score: 0.9659090909090909
Mean Score: 0.9659090909090909
Mean Score: 0.9659090909090909
Mean Score: 0.9550395256916996


In [33]:
data.head(3)

book_id        writer  st_state5x3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray       0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray       0.261259   
2             feluda_13_Bombayer_Bombete  Satyajit Ray       0.161039   

   st_state5x3_2  st_state5x3_3  st_state5x3_4  st_state5x3_5  state5x5_1  \
0       0.253602       0.207741       0.138053       0.182240    0.332685   
1       0.261148       0.217963       0.113027       0.146602    0.340206   
2       0.231818       0.218831       0.153247       0.235065    0.286290   

   state5x5_2  state5x5_3  ...  state7x7_48  state7x7_49      mean  median  \
0    0.282101    0.177043  ...     0.072464     0.094203  8.076395     7.0   
1    0.283505    0.185567  ...     0.058824     0.147059  7.318498     6.0   
2    0.298387    0.161290  ...     0.078014     0.134752  9.295515     8.0   

   mode   variance   std_dev  \
0     5  31.971834  5.654364   
1     3  27.927666  5.284663   
2     6  45.507333  6.745912   

                                      punc_state_mat          punc_st_state  \
0  [[0.52 0.13 0.03 0.32]\n [0.52 0.11 0.03 0.34]...  [0.56 0.11 0.04 0.29]   
1  [[0.53 0.14 0.03 0.31]\n [0.64 0.07 0.06 0.23]...  [0.55 0.12 0.04 0.29]   
2  [[0.51 0.08 0.03 0.38]\n [0.46 0.17 0.04 0.33]...  [0.55 0.09 0.03 0.33]   

   en_writer  
0          1  
1          1  
2          1  

[3 rows x 176 columns]

In [34]:
# PyTorch
import torch
from torch import nn

In [35]:
# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [36]:
y.head(2)

book_id        writer  en_writer
0               feluda_33_Noyon_Rahashya  Satyajit Ray          1
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          1

In [37]:
# Turn data into tensors
# Otherwise this causes issues with computations later on

# Convert to PyTorch tensors
X_tensor = torch.tensor(X.values, dtype=torch.float)
y_tensor = torch.tensor(y.en_writer.values, dtype=torch.long)

In [38]:
# Display the tensors
print("X Tensor:")
print(X_tensor.shape)
print("y Tensor:")
print(y_tensor)

X Tensor:
torch.Size([89, 38])
y Tensor:
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [39]:
# Split data into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_tensor,
                                                   y_tensor, 
                                                   test_size=0.15,
                                                   random_state=42)

len(X_train), len(X_test), len(y_train), len(y_test)

(75, 14, 75, 14)

In [40]:
class SpiralModel(nn.Module):
    def __init__(self, input_features, output_features, hidden_units=8):
        
        """Initializes all required hyperparameters for a multi-class classification model.

        Args:
            input_features (int): Number of input features to the model.
            out_features (int): Number of output features of the model
              (how many classes there are).
            hidden_units (int): Number of hidden units between layers, default 8.
        """
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(in_features=input_features, out_features=50),
            nn.ReLU(),
            nn.Linear(in_features=50, out_features=hidden_units**2),
            nn.Linear(in_features=hidden_units**2, out_features=hidden_units**3),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units**3, out_features=hidden_units**2),
            nn.Linear(in_features=hidden_units**2, out_features=output_features),

        )
        
    def forward(self, x):
        return self.linear_layer_stack(x)
        
        

# Create an instance of BlobModel and send it to the target device
model_5 = SpiralModel(input_features=38, 
                    output_features=3, 
                    hidden_units=10).to(device)
model_5

SpiralModel(
  (linear_layer_stack): Sequential(
    (0): Linear(in_features=38, out_features=50, bias=True)
    (1): ReLU()
    (2): Linear(in_features=50, out_features=100, bias=True)
    (3): Linear(in_features=100, out_features=1000, bias=True)
    (4): ReLU()
    (5): Linear(in_features=1000, out_features=100, bias=True)
    (6): Linear(in_features=100, out_features=3, bias=True)
  )
)

In [41]:
# Create loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_5.parameters(), 
                            lr=0.0003)

In [42]:
y_logits = model_5(X_test)
y_logits[:5]

tensor([[ 0.1061,  0.0902, -0.0909],
        [ 0.1028,  0.0964, -0.0904],
        [ 0.1063,  0.0917, -0.0909],
        [ 0.1049,  0.0898, -0.0908],
        [ 0.1041,  0.0971, -0.0895]], grad_fn=<SliceBackward0>)

In [43]:
y_pred_probs = torch.softmax(y_logits, dim=1)
y_pred_probs[:5]

tensor([[0.3565, 0.3508, 0.2927],
        [0.3549, 0.3526, 0.2925],
        [0.3563, 0.3511, 0.2925],
        [0.3562, 0.3509, 0.2929],
        [0.3550, 0.3525, 0.2925]], grad_fn=<SliceBackward0>)

In [44]:
y_preds = torch.argmax(y_pred_probs, dim=1)
y_preds[:5]

tensor([0, 0, 0, 0, 0])

In [45]:
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

torch.eq(torch.Tensor([1,3,3]), torch.Tensor([2,3,3]))

tensor([False,  True,  True])

In [46]:
accuracy_fn(torch.Tensor([1,1,1]), torch.Tensor([1,1,3]))

66.66666666666666

In [47]:
# Fit the model
torch.manual_seed(42)

# Set number of epochs
epochs = 1000

# Put data on target device
X_train, y_train = X_train.to(device), y_train.to(device)
X_test, y_test = X_test.to(device), y_test.to(device)

for epoch in range(epochs):
    ### Training
    model_5.train()
    
    # 1. Forward pass
    y_logits = model_5(X_train)
    y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1)
    
    # 2. Calculate loss and accuracy
    loss = loss_fn(y_logits, y_train)
    acc = accuracy_fn(y_train, y_pred)
    
    # 3. Optimizer zero grad
    optimizer.zero_grad()
    
    # 4. Loss backwards
    loss.backward()
    
    #5. Optimizer step
    optimizer.step()
    
    ### Testing
    model_5.eval()
    with torch.inference_mode():
        # 1. Forward pass
        test_logits = model_5(X_test)
        test_pred = torch.softmax(test_logits, dim=1).argmax(dim=1)
        # 2. Calculate test loss and accuracy
        test_loss = loss_fn(test_logits, y_test)
        test_acc = accuracy_fn(y_true=y_test,
                             y_pred=test_pred)
    # Print out what's happening
    if epoch % 100 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}, Acc: {acc:.2f}% | Test Loss: {test_loss:.5f}, Test Acc: {test_acc:.2f}%") 

Epoch: 0 | Loss: 1.06503, Acc: 50.67% | Test Loss: 1.06623, Test Acc: 28.57%
Epoch: 100 | Loss: 0.18523, Acc: 96.00% | Test Loss: 0.21014, Test Acc: 92.86%
Epoch: 200 | Loss: 0.03483, Acc: 98.67% | Test Loss: 0.20776, Test Acc: 92.86%
Epoch: 300 | Loss: 0.00307, Acc: 100.00% | Test Loss: 0.43350, Test Acc: 92.86%
Epoch: 400 | Loss: 0.00078, Acc: 100.00% | Test Loss: 0.54151, Test Acc: 92.86%
Epoch: 500 | Loss: 0.00035, Acc: 100.00% | Test Loss: 0.60459, Test Acc: 92.86%
Epoch: 600 | Loss: 0.00019, Acc: 100.00% | Test Loss: 0.65849, Test Acc: 92.86%
Epoch: 700 | Loss: 0.00011, Acc: 100.00% | Test Loss: 0.70336, Test Acc: 92.86%
Epoch: 800 | Loss: 0.00007, Acc: 100.00% | Test Loss: 0.74038, Test Acc: 92.86%
Epoch: 900 | Loss: 0.00005, Acc: 100.00% | Test Loss: 0.77137, Test Acc: 92.86%
