<div style="text-align: center;background-color: gold; padding: 25px; border-radius: 5px; margin-bottom: 10px;">
    <h2> AUTHORSHIP ATTRIBUTION USING SENTENCE LENGTH AND PUNCTUATION PATTERN </h2>
</div>

* Main Idea : `Harun Or Rashid Sir` 😊✨
* Coding    : `Tanbeer Jubaer` 🌟 and `Minhazul Islam` 🏆
<!-- 😊
✨
🌟
👍
❤️
🎉
🌸
🚀
🎈
🎂
📚
🎵
🎲
🏆
🎥
🍕
🍎
🚗
⏰ -->

<div style="background-color: lightblue; padding: 15px; border-radius: 5px; margin-bottom: 10px;">

### Section 1: Import Data

Will add later

</div>

<div style="background-color: lightgreen; padding: 15px; border-radius: 5px; margin-bottom: 10px;">

### Section 2: Pre-Processing

Will add later

</div>

<div style="background-color: lightcoral; padding: 15px; border-radius: 5px; margin-bottom: 10px;">

### Section 3: Plotting

WIll add later

</div>


<div style="text-align: center;">
    <h2> 1. Import Necessary Libraries</h2>
</div>

In [ ]:
# Regular EDA(exploratory data analysis) and plotting libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
%matplotlib inline

from tqdm import tqdm
import string
import statistics
import re
import joblib
import random
import statistics
from collections import Counter
from scipy import stats
import os
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics.pairwise import cosine_similarity
import zipfile
from matplotlib.lines import Line2D

<div style="text-align: center; background-color: lightgreen;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h2> 2. PRE-PROCESSING STEPS </h2>
</div>
<ol>
    <li><h3>Sentence Length</h3></li>
    <li><h3>Punctuations</h3></li>
</ol>
<div style="text-align: center; background-color: lightgreen;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h2> At First we discover the Sentence Length Patterns</h2>
</div>

In [ ]:
# Necessary Functions

def read_stories(paths):
    '''
    Read All the stories from a folder and return an array of sentence.
    '''
    sents = []
    for path in paths:
        # File path with Bengali characters
        file_path_bangla = path
        # Open the file using triple quotes around the file path
        with open(f"""{file_path_bangla}""", 'r', encoding='utf-8') as file:
            content = file.read()
        sent = make_sentences(content)
        sents.append(sent)
    # Convert the 2d array into 1d array
#     ments = [element for row in sents for element in row]
    return sents


def remove_noise(sentence):
    '''
    Removes noise from the dataset
    '''
    # Remove punctuation
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))
    # Remove extra spaces and newlines
    sentence = ' '.join(sentence.split())
    return sentence

def make_sentences(content):
    '''
    Takes a full story of a book or Multiple Books
    And convert it into a list of sentences.
    '''
    import re

    # Split the story into sentences using full stops (".") as delimiters
    # sentences = story.strip().split('।')
    sentences = re.split(r'[।?!]', content)

    # Remove any leading/trailing whitespaces from each sentence, remove punctuation and
    # other noise

    # Filter out empty sentences (if any) using the filter function
    sentences = list(filter(None, sentences))
    cleaned_sentences = [remove_noise(sentence) for sentence in sentences if sentence.strip()]

    # Print the list of cleaned sentences
    return cleaned_sentences

In [ ]:
# Books path in a directory
paths = []
for dirname, _, filenames in os.walk('/kaggle/input/bookscollection/Feluda all copy'):
    for filename in filenames:
        paths.append(os.path.join(dirname, filename))
paths[0]

<div style="text-align: center;">
    <h4> 2.1 Make List of Sentences From a Book</h4>
</div>

In [ ]:
def create_lenarray(path):
    '''
    Chill
    '''
    paths = []
    for dirname, _, filenames in os.walk(path):
        for filename in filenames:
            paths.append(os.path.join(dirname, filename))

    sentences = read_stories(paths)
    lenarr = []
    for block in sentences:
        len_ofS = [len(sentence.split()) for sentence in block]
        lenarr.append(len_ofS)
    return sentences, lenarr

In [ ]:
sentences, lenarr = create_lenarray('/kaggle/input/bookscollection/Feluda all copy')

In [ ]:
sentences[0][:10]

In [ ]:
lenarr[0][:10]

In [ ]:
# check a random sentence from the text
rand_index = np.random.randint(0, len(sentences[10]))
print(f'''Index = {rand_index},  sentence = {sentences[10][rand_index]}, 
length = {len(sentences[10][rand_index].split())}''')

<div style="text-align: center;">
    <h4> 2.2 Calculate Central Tendency, Variance etc</h4>
</div>

In [ ]:
numbers = lenarr[0]

# Calculate mean
mean = statistics.mean(numbers)

# Calculate median
median = statistics.median(numbers)

# Calculate quartiles
quartiles = statistics.quantiles(numbers, n=4)

# Calculate mode
mode_data = Counter(numbers)
mode = mode_data.most_common(1)[0][0]

# Calculate variance
variance = statistics.variance(numbers)

# Calculate standard deviation
std_dev = statistics.stdev(numbers)


print(f"Mean: {mean:.2f}")
print("Median:", median)
print("Quartiles:", quartiles)
print("Mode:", mode)
print(f"Variance: {variance:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")

###  Create two Folders
1. Sentence
2. Punctuation

In [ ]:
folder_path = os.path.join(os.getcwd(), 'Sentence')

# Create the folder
os.makedirs(folder_path, exist_ok=True)

In [ ]:
folder_path = os.path.join(os.getcwd(), 'Punctuation')

# Create the folder
os.makedirs(folder_path, exist_ok=True)

<div style="text-align: center; background-color: lightblue;padding: 45px; border-radius: 5px; margin-bottom: 20px;">
    <h2>3 PLOTTING SECTION </h2>
</div>

**NECESSARY FUNCTIONS**

In [ ]:
sentences1, lenarr1 = create_lenarray('/kaggle/input/bookscollection/Feluda all copy')
sentences2, lenarr2 = create_lenarray('/kaggle/input/bookscollection/Rabindranath_Novels_all')
sentences3, lenarr3 = create_lenarray('/kaggle/input/bookscollection/Himu_all')
sentences4, lenarr4 = create_lenarray('/kaggle/input/bookscollection/Misir_Ali_all')

In [ ]:
print(f'''
Number Of Books SR = {len(lenarr1)}
Number Of Books RT = {len(lenarr2)}
Number Of Books HA = {len(lenarr3)}
''')

In [ ]:
sentences1[0][:10]

In [ ]:
paths = []
for dirname, _, filenames in os.walk('/kaggle/input/bookscollection/Feluda all copy'):
    for filename in filenames:
        paths.append(os.path.join(filename))
paths[:10]

In [ ]:
name_list = [['ফেলুদা_টিনটোরেটোর_যীশু_সত্যজিৎ_রায়', 'ফেলুদা_বাদশাহী_আংটি_সত্যজিৎ_রায়', 'ফেলুদা_নেপোলিয়নের_চিঠি_সত্যজিৎ_রায়'],
             ['মালঞ্চ ১৯৩৪', 'রাজর্ষি ১৮৮৭', 'চার অধ্যায় ১৯৩৪'],
             ['এবং হিমু (১৯৯৫)', 'হিমুর হাতে কয়েকটি নীলপদ্ম (১৯৯৬)', 'হিমুর আছে জল (২০১১)']
             ]

In [ ]:
sentences3[6][:3]

In [ ]:
lenarr2[6][:20]

## Check a Sentence's type using ML model

In [ ]:
# from transformers import BertTokenizer, TFBertModel,AutoTokenizer
# import tensorflow as tf
# tokenizer = AutoTokenizer.from_pretrained('sagorsarker/bangla-bert-base')

In [ ]:
## load model
# loaded_model = joblib.load('/kaggle/input/model1/SentencTypeClassifier_0.pkl')

In [ ]:
# loaded_model

In [ ]:
def custom_test_up(text):
    inputs=tokenizer(text,return_tensors="tf")
    tf_outputs = loaded_model(inputs)                                  
    tf_predictions =np.argmax( tf.nn.softmax(tf_outputs[0], axis=-1) )
    return  tf_predictions

In [ ]:
# bn = 0
# ind = random.randint(0, len(lenarr2[0]))
# rs = sentences2[bn][ind]
# rs, custom_test_up(rs)

<div style="text-align: center;">
    <h4> 3.4 Markov Property Of Sentence Length </h4>
    <h2>📊📈📉📊📈📉📊📈📉</h2>
</div>

This is a very important topic in our study. <br>
Steps in finding pattern using Probablity and Markov property 
1. Divide Sentences Lengths in some Categories or States. 
2. Design an Algorithm to Plot the Pattern
3. Plot the State Matrix
4. Plot the Stationary State Matrix

<div style="text-align: center;">
    <h4> 3.4.1 Make Categories or States </h4>
</div>


In [ ]:
def catsentwo(x):
    '''
    Changes A length to an assumed category.
    '''
    if x <= 3:
        x = 0
    elif x <= 6:
        x = 1
    elif x <= 9:
        x = 2
    elif x <= 12:
        x = 3
    elif x <= 15:
        x = 4
    else:
        x = 5
    return x


sencat = {
    "sent_category": ["0<x<=5", "5<x<=10", "10<x<=15", "x>15"],
    "label": [0, 1, 2, 3],
    'state': ['A', 'B', 'C', 'D']
}

sencat = {
    "sent_category": ["0<x<=3", "3<x<=6", "6<x<=9", "9<x<=12", "12<x<=15", "x>15"],
    "label": [0, 1, 2, 3, 4, 5 ],
    'state': ['A', 'B', 'C', 'D', 'E', 'F']
}

labeldf = pd.DataFrame(sencat)
labeldf

In [ ]:
def catsen(x, states = 10, dif = 2):
    '''
    Changes A length to an assumed category.
    
    Args:
    x : is a length of something (ie. Word Sentence)
    states : Number of considered states default is 10
    dif : Difference Between States
    '''
    return min(states-1, (x - 1) // dif)

In [ ]:
tem = lenarr1[0][:10]
print(tem)
[catsen(x, 2, 10) for x in tem]

<div style="text-align: center;">
    <h4> 3.4.2 Algorithm for <span style="text-shadow: 2px 2px 4px #000000;">N</span> Categories or States </h4>
</div>

In [ ]:
def showA(arr, n=10, dif=2):
    '''
    Converts an array ready to be solved using Linear Algebra
    
    Args:
    arr : The array that we are converting to the state matrix.
    states : Number of considered states default is 10
    dif : Difference Between States
    '''
    # Initialize a nxn array with zeros
    # n = 4
    A = np.ones((n, n))
    # Raff 
    rff = arr
    for i in range(len(rff)-1):
        first_ind = catsen(rff[i], states=n, dif=dif)
        second_ind = catsen(rff[i+1], states=n, dif=dif)
        A[first_ind, second_ind] += 1
        
    # Convert it into probablity the required math analysis is in my notebook
    row_sums = A.sum(axis=1, keepdims=True)
    normalized_A = A / row_sums
    rnd_A = np.round(normalized_A, decimals=8)
#     print(f'Matrix A = \n{rnd_A}')
    return rnd_A

def stationary_state(matrix):
    # Calculate the stationary state vector using eigenvalue decomposition
    eigenvalues, eigenvectors = np.linalg.eig(matrix.T)
    stationary_state_index = np.argmin(np.abs(eigenvalues - 1.0))
    stationary_state_vector = np.real(eigenvectors[:, stationary_state_index])
    stationary_state_vector /= stationary_state_vector.sum()
    return stationary_state_vector

In [ ]:
t = showA(lenarr2[0],5, 3)
t, stationary_state(t)

<div style="text-align: center;">
    <h4> 3.4.2 Algorithm for <span style="text-shadow: 2px 2px 4px #000000;">Six</span> Categories or States </h4>
</div>

In [ ]:
def igenmatrix2(arr):
    '''
    Converts an array ready to be solved using Linear Algebra
    '''
    # Initialize a nxn array with zeros
    n = 6
    A = np.zeros((n, n))
    # Raff 
    rff = arr
    for i in range(len(rff)-1):
        first_ind = catsentwo(rff[i])
        second_ind = catsentwo(rff[i+1])
        A[first_ind, second_ind] += 1
        
    # Convert it into probablity the required math analysis is in my notebook
    row_sums = A.sum(axis=1, keepdims=True)
    normalized_A = A / row_sums
    rnd_A = np.round(normalized_A, decimals=2)
#     print(f'Matrix A = \n{rnd_A}')
    
    # Transpose of the matrix
    AT = rnd_A.T
    
    # Identity matrix
    identity_matrix = np.eye(n)

    # Subtract identity matrix from the transposed matrix
    ATI = AT - identity_matrix
    
    return ATI

def sentRank2(matrix):
    '''
    Returns the stationary matrix for a given Sentence length Array.
    '''
    # Create a new matrix with the last column replaced
    new_column = np.array([1, 1, 1, 1, 1, 1])
    modified_matrix = matrix.copy()
    modified_matrix[-1] = new_column
    #print(modified_matrix)
    
    # Right-hand side vector of the given equations
    b = np.array([0, 0, 0, 0, 0, 1])
    # Solve the system of equation now
    solution = np.linalg.solve(modified_matrix, b)
    solution = np.round(solution, decimals=2)
    
    return solution

def showA2(arr, n=6):
    '''
    Converts an array ready to be solved using Linear Algebra
    '''
    # Initialize a nxn array with zeros
    # n = 6
    A = np.ones((n, n))
    # Raff 
    rff = arr
    for i in range(len(rff)-1):
        first_ind = catsentwo(rff[i])
        second_ind = catsentwo(rff[i+1])
        A[first_ind, second_ind] += 1
        
    # Convert it into probablity the required math analysis is in my notebook
    row_sums = A.sum(axis=1, keepdims=True)
    normalized_A = A / row_sums
    rnd_A = np.round(normalized_A, decimals=2)
#     print(f'Matrix A = \n{rnd_A}')
    return rnd_A


In [ ]:
print(stationary_state(showA2(lenarr2[1])))

In [ ]:
showA2(lenarr2[1], 10)

In [ ]:
P = lenarr2[1]
# Calculate the stationary state vector using eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(showA2(P).T)
stationary_state_index = np.argmin(np.abs(eigenvalues - 1.0))
stationary_state_vector = np.real(eigenvectors[:, stationary_state_index])
stationary_state_vector /= stationary_state_vector.sum()
print(stationary_state_vector)
sentRank2(igenmatrix2(lenarr2[1]))

In [ ]:
st_matArr1 = []
for i in range(len(lenarr1)):
    st_matArr1.append(sentRank2(igenmatrix2(lenarr1[i])))
st_matArr2 = []
for i in range(len(lenarr2)):
    st_matArr2.append(sentRank2(igenmatrix2(lenarr2[i])))
st_matArr3 = []
for i in range(len(lenarr3)):
    st_matArr3.append(sentRank2(igenmatrix2(lenarr3[i])))
    
print(f'Books Of SR = {len(st_matArr1)},  Books Of RT = {len(st_matArr2)}, Books Of HA = {len(st_matArr3)}')

In [ ]:
st_matArr1 = []
for i in range(len(lenarr1)):
    st_matArr1.append(stationary_state(showA(lenarr1[i], 5, 3)))
st_matArr2 = []
for i in range(len(lenarr2)):
    st_matArr2.append(stationary_state(showA(lenarr2[i], 15, 2)))
st_matArr3 = []
for i in range(len(lenarr3)):
    st_matArr3.append(stationary_state(showA(lenarr3[i], 15, 2)))
    
print(f'Books Of SR = {len(st_matArr1)},  Books Of RT = {len(st_matArr2)}, Books Of HA = {len(st_matArr3)}')

In [ ]:
def calculate_avg(array):
    # Calculate the means for each elementarray
    num = len(array)
    num_elements = len(array[0])  

    # Calculate the sum for each element position
    sums = [sum(inner_array[i] for inner_array in array) for i in range(num_elements)]
    # Calculate the means by dividing the sums by the number of arrays
    means = [sums[i] / num for i in range(num_elements)]
    means = np.round(means, decimals=3)
    return means

In [ ]:
print(f'Writter 1 --> {calculate_avg(st_matArr1)}')
print(f'Writter 2 --> {calculate_avg(st_matArr2)}')
print(f'Writter 3 --> {calculate_avg(st_matArr3)}')

<div style="text-align: center;">
    <h4> 3.4.3 Plot the States Matrix </h4>
</div>

In [ ]:
# N States 
def state_matrix_two(mat1, mat2, mat3, cmi = 1, save_path = None, n=10):
    '''
    Plots Difference of The Heatmap of The State Matrix of Two different Writters. 
    '''
    # cmaps that i want to use
    cmaps = ['viridis', 'inferno', 'plasma', 'cividis']
    fig, axes = plt.subplots(1, 3, figsize=(15, 5), gridspec_kw={'width_ratios': [1, 1, 1]})
    plt.subplots_adjust(wspace = .8) 
    
    im1 = axes[0].matshow(mat1, cmap=cmaps[cmi], vmin=0, vmax=1)
    axes[0].set_title('Satyajit Ray')

    im2 = axes[1].matshow(mat2, cmap=cmaps[cmi], vmin=0, vmax=1)
    axes[1].set_title('Rabindranath Tagore')
    
    im3 = axes[2].matshow(mat3, cmap=cmaps[cmi], vmin=0, vmax=1)
    axes[2].set_title('Humayun Ahmed')
    
    rownum = n
    # Add text annotations
    for i in range(rownum):
        for j in range(rownum):
            axes[0].text(j, i, f'{matrix1[i, j]:.2f}', ha="center", va="center", color="w")
            axes[1].text(j, i, f'{matrix2[i, j]:.2f}', ha="center", va="center", color="w")
            axes[2].text(j, i, f'{matrix3[i, j]:.2f}', ha='center', va='center', color='w')

    
    # Set x-ticks and y-ticks labels from 'A' to 'J'
    tick_labels = list(string.ascii_uppercase)[:rownum]
    for ax in axes:
        ax.set_xticks(np.arange(rownum))
        ax.set_yticks(np.arange(rownum))
        ax.set_xticklabels(tick_labels)
        ax.set_yticklabels(tick_labels)
        ax.tick_params(axis='both', which='both', length=0)

    plt.tight_layout()
    plt.colorbar(im1, ax=axes)
    if save_path:
        plt.savefig(save_path)
    plt.show()

In [ ]:
matrix1 = showA(lenarr1[0])
matrix2 = showA(lenarr2[0])
matrix3 = showA(lenarr3[0])
state_matrix_two(matrix1, matrix2, matrix3, cmi=1)

In [ ]:
def book_list(path):
    '''
    Returns the book list of in a directory
    '''
    # Create all the book names list
    np.random.seed(42)
    paths = []
    for dirname, _, filenames in os.walk(path):
        for filename in filenames:
            paths.append(os.path.join(filename.replace('.txt', '')))
    return paths

In [ ]:
sr_book_list = book_list('/kaggle/input/bookscollection/Feluda all copy')
rt_book_list = book_list('/kaggle/input/bookscollection/Rabindranath_Novels_all')
ha_book_list = book_list('/kaggle/input/bookscollection/Himu_all')
ma_book_list = book_list('/kaggle/input/bookscollection/Misir_Ali_all')

In [ ]:
# ha_book_list

In [ ]:
# N is the number of comparision you want to see
N = 2

# number of states
states = 6
d = 3
for i in range(N):
    print(f'{i+1} {sr_book_list[i]}\t{ma_book_list[i]}\t{ha_book_list[i]}')
    if i == 200:
        pass
    else:
        path = f'/kaggle/working/Sentence/output_matrix_{i}.png'
        matrix1 = showA(lenarr1[i], states, d)
        matrix2 = showA(lenarr4[i], states, d)
        matrix3 = showA(lenarr3[i], states, d)
        state_matrix_two(matrix1, matrix2, matrix3, cmi=1, n=states)
    
print('<---------------ENDED----------->')

## List of Common Marker Options in Matplotlib

1. `.` - Point marker
2. `,` - Pixel marker
3. `o` - Circle marker
4. `v` - Triangle Down marker
5. `^` - Triangle Up marker
6. `<` - Triangle Left marker
7. `>` - Triangle Right marker
8. `1` - Tri Down marker
9. `2` - Tri Up marker
10. `3` - Tri Left marker
11. `4` - Tri Right marker
12. `s` - Square marker
13. `p` - Pentagon marker
14. `*` - Star marker
15. `h` - Hexagon1 marker
16. `H` - Hexagon2 marker
17. `+` - Plus marker
18. `x` - X marker
19. `D` - Diamond marker
20. `d` - Thin Diamond marker


<div style="text-align: center;" color='blue'>
    <h4> 3.4.3 Plot the Relation of the State Matrix </h4>
</div>

In [ ]:
paths = []
for dirname, _, filenames in os.walk('/kaggle/input/bookscollection/Rabindranath_Novels_all'):
    for filename in filenames:
        paths.append(os.path.join(dirname, filename))
paths[:10]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def get_cosine_similarity(array):
    '''
    Returns the cosine Similarity Between the First book and All the other books
    '''
    cosine_similarity_score = []
    for i in range(1, len(array)):
        mat1 = showA(array[0],  states, d)
        mat2 = showA(array[i],  states, d)
        # Reshape matrices into 1-D arrays before calculating cosine similarity
        cosine_similarity_score.append(cosine_similarity(mat1.reshape(1, -1), mat2.reshape(1, -1))[0, 0])
    return cosine_similarity_score


In [ ]:
sim_arr1 = get_cosine_similarity(lenarr1)
sim_arr2 = get_cosine_similarity(lenarr2)
sim_arr3 = get_cosine_similarity(lenarr3)

In [ ]:
def scatter_plot_with_lines(*arrays, save_path = None):
    '''
    Create subplots with scatter points and lines connecting them for multiple arrays.
    '''
    max_length = max(len(arr) for arr in arrays)
    tnames = ['Feluda Series Satyajit Ray', 'Novels of Rabindranath Tagore', 'Himu Series Humayun Ahmed']
    marks = ['o', 'x', '*']
    colors = ['coral', 'blue', 'red']

    fig, axs = plt.subplots(1, len(arrays), figsize=(18, 6), sharey=True)

    for i, (array, ax, color) in enumerate(zip(arrays, axs, colors)):
        x_values = list(range(1, len(array) + 1))
        ax.scatter(x_values, array, label=f'{tnames[i]}', marker=marks[i], color=color)
        ax.plot(x_values, array, linestyle='-', color=color)
        ax.set_xlabel('Book Number')
        ax.set_title(f'{tnames[i]}')
        ax.set_ylim([0.5, 1])

    axs[0].set_ylabel('Cosine Similarity')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path)  
    plt.show()


In [ ]:
# Example usage:
scatter_plot_with_lines(sim_arr1, sim_arr2, sim_arr3, save_path = '/kaggle/working/Sentence/sentence_matrix_corelation.png')

<div style="background-color: lightcoral; padding: 15px; border-radius: 5px; margin-bottom: 10px; text-align: center;">

 ### Now I need to make the DataFrame Adding these features.

</div>

In [ ]:
# sr_book_list

### First For Satyajit Ray

In [ ]:
# Set the Value of states and difference
states_n_dif = [[5,3],[2,10], [3,10],[3,8], [3,6], [4,4], [5,2], [6,3], [7,3], [7,2], [8,3], [10,2]]
states_n_dif[:3]

In [147]:
num_of_cc = 0
for x in states_n_dif:
    num_of_cc += (x[0]+1)*x[0]
num_of_cc+7

465

In [154]:
def add_features(array, data):
    '''
    This is a very bad luck.
    '''
    for value in states_n_dif:
        states = value[0]
        d = value[1]

        st_matArr1 = []
        for i in range(len(array)):
            st_matArr1.append(stationary_state(showA(array[i], states, d)))

        state_mat1 = []
        for i in range(len(array)):
            state_mat1.append(showA(array[i], states, d))

        empty_states = np.zeros((len(array), states))
        for i, val in enumerate(st_matArr1):
            for j in range(states):
                empty_states[i][j] = val[j]

        for s in range(states):
            data[f'st_state{states}x{d}_{s+1}'] = empty_states[:, s]
            
        empty_states = np.zeros((len(array), states))
        for i, val in enumerate(st_matArr1):
            for j in range(states):
                empty_states[i][j] = val[j]
                

def add_features2(array, data):
    '''
    Bismillah
    '''
    for value in states_n_dif:
        states = value[0]
        d = value[1]
        
        # This is the stationary state
        st_state = []
        for i in range(len(array)):
            st_state.append(stationary_state(showA(array[i], states, d)))
        
        # This is the state matrix
        state_mat1 = []
        for i in range(len(array)):
            state_mat1.append(showA(array[i], states, d))

        # Add stationary states in the dataframe
        for s in range(states):
            data[f'st_state{states}_dif{d}_{s+1}'] = np.array(st_state)[:, s]
        for s in range(states):
            for k in range(states):
                data[f'state{states}_dif{d}_{states*s+k+1}'] = np.array(state_mat1)[:, s, k]
        
            

    
def add_means(array, data):
    means = []
    medians = []
    modes = []
    variances = []
    std_devs = []
    
    for i in range(len(array)):
        # means
        means.append(statistics.mean(array[i]))
        # median
        medians.append(statistics.median(array[i]))
        # mode
        mode_data = Counter(lenarr1[i])
        modes.append(mode_data.most_common(1)[0][0])
        # variance
        variances.append(statistics.variance(array[i]))
        # std deviation
        std_devs.append(statistics.stdev(array[i]))
    data['mean'] = means
    data['median'] = medians
    data['mode'] = modes
    data['variance'] = variances
    data['std_dev'] = std_devs

In [155]:
# Satyajit Ray
srdata = (
{
    'book_id' : sr_book_list,
    'writer': 'Satyajit Ray',
})
add_features2(lenarr1, srdata)
add_means(lenarr1, srdata)

In [156]:
srdata = pd.DataFrame(srdata)
print(srdata.shape)
srdata.head(2)

(35, 465)


book_id        writer  st_state5_dif3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray          0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          0.261259   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.253602          0.207741          0.138053          0.182240   
1          0.261148          0.217963          0.113027          0.146602   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  \
0       0.332685       0.282101       0.177043  ...         0.078014   
1       0.340206       0.283505       0.185567  ...         0.054054   

   state10_dif2_97  state10_dif2_98  state10_dif2_99  state10_dif2_100  \
0         0.092199         0.056738         0.035461          0.092199   
1         0.135135         0.027027         0.054054          0.135135   

       mean  median  mode   variance   std_dev  
0  8.076395     7.0     5  31.971834  5.654364  
1  7.318498     6.0     3  27.927666  5.284663  

[2 rows x 465 columns]

In [157]:
srdata.columns

Index(['book_id', 'writer', 'st_state5_dif3_1', 'st_state5_dif3_2',
       'st_state5_dif3_3', 'st_state5_dif3_4', 'st_state5_dif3_5',
       'state5_dif3_1', 'state5_dif3_2', 'state5_dif3_3',
       ...
       'state10_dif2_96', 'state10_dif2_97', 'state10_dif2_98',
       'state10_dif2_99', 'state10_dif2_100', 'mean', 'median', 'mode',
       'variance', 'std_dev'],
      dtype='object', length=465)

In [ ]:
# srdata['st_state5_1']

In [158]:
# states = 3
# array = lenarr2
# state_mat1 = []
# for i in range(len(array)):
#     state_mat1.append(showA(array[i], states, d))
# tem = np.array(state_mat1)
# tem

In [159]:
# tem.shape

In [160]:
# tem[:, 2, 0]

In [161]:
# states = 3
# for s in range(states):
#     for k in range(states):
#         srdata[f'state{states}_{states*s+k+1}'] = tem[:, s, k]
# srdata

In [ ]:
# import numpy as np

# # Create a sample array
# arr = np.random.random((10, 3, 3))

# # Example 1: Access the entire first block
# first_block = arr[0, :, :]

# # Example 2: Access the entire second row of all blocks
# second_row_all_blocks = arr[:, 1, :]

# # Example 3: Access the element in the second column of the third row of the fifth block
# element = arr[4, 2, 1]

# # Example 4: Access the last column of all blocks
# last_column_all_blocks = arr[:, :, -1]

# # Example 5: Access a subarray containing the first two blocks
# subarray = arr[:2, :, :]

# # Example 6: Access a subarray containing the first block, excluding the first row
# subarray_no_first_row = arr[0, 1:, :]

# # Example 7: Access a subarray containing the first block, excluding the first column
# subarray_no_first_column = arr[0, :, 1:]

# # Example 8: Use boolean indexing to select blocks based on a condition
# condition = arr[:, 0, 0] > 0.5
# selected_blocks = arr[condition, :, :]

# # Example 9: Use fancy indexing to select specific blocks
# selected_blocks_fancy = arr[[0, 3, 6], :, :]

# # Example 10: Modify values in a subarray
# arr[1:3, :, :] = 0

# # Print the original array and selected values for verification
# print("Original Array:")
# print(arr)
# print("\nSelected Values:")
# print("Example 1:", first_block)
# print("Example 2:", second_row_all_blocks)
# print("Example 3:", element)
# print("Example 4:", last_column_all_blocks)
# print("Example 5:", subarray)
# print("Example 6:", subarray_no_first_row)
# print("Example 7:", subarray_no_first_column)
# print("Example 8:", selected_blocks)
# print("Example 9:", selected_blocks_fancy)
# print("Example 10 (Modified Array):")
# print(arr)


In [162]:
# t = np.array(st_matArr1)[:,0]t

In [ ]:
# states = 5
# for s in range(states):
#     srdata[f'st_state{states}_{s+1}'] = np.array(st_matArr1)[:, s]
# srdata

In [ ]:
# empty_states = np.zeros((35, 5))
# for i, val in enumerate(st_matArr1):
#     for j in range(5):
#         empty_states[i][j] = val[j]
# empty_states
# for s in range(states) :
#     srdata[f'st_state{states}_{s+1}'] = empty_states[:, s]

### For Rabindranath Tagore 

In [163]:
len(lenarr2)

13

In [165]:
rtdata = (
{
    'book_id' : rt_book_list,
    'writer': 'Rabindranath',
})

add_features2(lenarr2, rtdata)
add_means(lenarr2, rtdata)

In [166]:
rtdata = pd.DataFrame(rtdata)
print(rtdata.shape)
rtdata.head(2)

(13, 465)


book_id        writer  st_state5_dif3_1  st_state5_dif3_2  \
0     JogaJog-1929  Rabindranath          0.066800          0.214208   
1  Choturongo-1916  Rabindranath          0.056667          0.186215   

   st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  state5_dif3_1  \
0          0.228725          0.181805          0.308462       0.155496   
1          0.184184          0.185542          0.387392       0.178571   

   state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  state10_dif2_97  \
0       0.329759       0.174263  ...         0.120253         0.091772   
1       0.214286       0.238095  ...         0.094488         0.129921   

   state10_dif2_98  state10_dif2_99  state10_dif2_100       mean  median  \
0         0.074367         0.041139          0.188291  10.812376     9.0   
1         0.078740         0.070866          0.271654  12.296982    11.0   

   mode   variance   std_dev  
0     5  45.271556  6.728414  
1     3  70.207554  8.378995  

[2 rows x 465 columns]

### For Humayun Ahmed

In [167]:
hadata = (
{
    'book_id' : ha_book_list,
    'writer': 'Humayun Ahmed',
})

add_features2(lenarr3, hadata)
add_means(lenarr3, hadata)

hadata = pd.DataFrame(hadata)
print(hadata.shape)
hadata.head(2)

(21, 465)


book_id         writer  st_state5_dif3_1  \
0  EkjonHimuoKoektiJijhipoka(1999)  Humayun Ahmed          0.245212   
1             dorojar_opashe(1992)  Humayun Ahmed          0.194515   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.358967          0.214452          0.106210          0.075160   
1          0.414374          0.237332          0.099575          0.054204   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  \
0       0.312426       0.368047       0.176331  ...         0.092593   
1       0.235646       0.416268       0.199761  ...         0.050000   

   state10_dif2_97  state10_dif2_98  state10_dif2_99  state10_dif2_100  \
0         0.037037         0.018519         0.018519          0.055556   
1         0.050000         0.025000         0.025000          0.050000   

       mean  median  mode   variance   std_dev  
0  6.351841     6.0     5  15.316102  3.913579  
1  6.305803     6.0     3  11.763472  3.429792  

[2 rows x 465 columns]

### Humayun Ahmed Misir Ali

In [168]:
madata = ({
    'book_id' : ma_book_list,
    'writer': 'Humayun Ahmed',
})

add_features2(lenarr4, madata)
add_means(lenarr4, madata)

madata = pd.DataFrame(madata)
print(madata.shape)
madata.head(2)

(21, 465)


book_id         writer  st_state5_dif3_1  \
0       MisirAli-10-TondraBilash  Humayun Ahmed          0.209847   
1  MisirAli-17-MisirAlirUnsolved  Humayun Ahmed          0.246278   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.393959          0.228118          0.101190          0.066886   
1          0.394624          0.221222          0.091575          0.046302   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  \
0       0.290191       0.389646       0.194823  ...         0.076923   
1       0.313603       0.385254       0.203531  ...         0.162791   

   state10_dif2_97  state10_dif2_98  state10_dif2_99  state10_dif2_100  \
0         0.051282         0.025641         0.025641          0.025641   
1         0.093023         0.093023         0.046512          0.023256   

       mean  median  mode   variance   std_dev  
0  6.318941     6.0     5  13.199716  3.633141  
1  6.000515     5.0     3  12.263063  3.501866  

[2 rows x 465 columns]

In [169]:
data = pd.concat([srdata, rtdata, hadata, madata], axis=0)
data.head(2)

book_id        writer  st_state5_dif3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray          0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          0.261259   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.253602          0.207741          0.138053          0.182240   
1          0.261148          0.217963          0.113027          0.146602   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  \
0       0.332685       0.282101       0.177043  ...         0.078014   
1       0.340206       0.283505       0.185567  ...         0.054054   

   state10_dif2_97  state10_dif2_98  state10_dif2_99  state10_dif2_100  \
0         0.092199         0.056738         0.035461          0.092199   
1         0.135135         0.027027         0.054054          0.135135   

       mean  median  mode   variance   std_dev  
0  8.076395     7.0     5  31.971834  5.654364  
1  7.318498     6.0     3  27.927666  5.284663  

[2 rows x 465 columns]

In [170]:
data.shape

(90, 465)

In [171]:
data = data.reset_index(drop=True)

In [172]:
data['book_id'][88]

'MisirAli-21-SabhdhanMisirAli'

In [173]:
data.columns

Index(['book_id', 'writer', 'st_state5_dif3_1', 'st_state5_dif3_2',
       'st_state5_dif3_3', 'st_state5_dif3_4', 'st_state5_dif3_5',
       'state5_dif3_1', 'state5_dif3_2', 'state5_dif3_3',
       ...
       'state10_dif2_96', 'state10_dif2_97', 'state10_dif2_98',
       'state10_dif2_99', 'state10_dif2_100', 'mean', 'median', 'mode',
       'variance', 'std_dev'],
      dtype='object', length=465)

In [174]:
data.writer.value_counts()

writer
Humayun Ahmed    42
Satyajit Ray     35
Rabindranath     13
Name: count, dtype: int64

<div style="text-align: center; background-color: lightgreen;padding: 45px; border-radius: 5px; margin-bottom: 10px;">
    <h2> Now Discover the Punctuation Pattern </h2>
    <h4> At First Necessary Functions </h4>
</div>

In [175]:
# List of Punctuation we are considering
plist = ['।', ',', '?', '!']


def make_punctuations(content):
    '''
    Takes a full story of a book or Multiple Books
    And convert it into a list of punctuations.
    '''
    flist = []
    for text in content:
        if text in plist:
            flist.append(text)
    return flist

def read_stories_forPunc(paths):
    '''
    Read All the stories from a folder and return an array of Punctuations.
    '''
    puncs = []
    for path in paths:
        # File path with Bengali characters
        file_path_bangla = path
        # Open the file using triple quotes around the file path
        with open(f"""{file_path_bangla}""", 'r', encoding='utf-8') as file:
            content = file.read()
        sent = make_punctuations(content)
        puncs.append(sent)
    # Convert the 2d array into 1d array
#     ments = [element for row in sents for element in row]
    return puncs

def catpun(x):
    '''
    Changes A punctuations to an assumed category.
    '''
    if x == '।':
        x = 0
    elif x == '?':
        x = 1
    elif x == '!':
        x = 2
    else:
        x = 3
    return x

In [176]:
puncat = {
    "Punc_category": ["।", "?", "!", ","],
    "label": [0, 1, 2, 3],
    'State': ['A', 'B', 'C', 'D']
}
labeldf = pd.DataFrame(puncat)
labeldf

Punc_category  label State
0             ।      0     A
1             ?      1     B
2             !      2     C
3             ,      3     D

<div style="text-align: center; background-color: lightblue;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h3> First Plot the Sequence of Punctuation in line Plot  </h3>
</div>

In [177]:
def igenmatrix_Punc(arr):
    '''
    Converts an array ready to be solved using Linear Algebra
    '''
    # Initialize a nxn array with zeros
    n = 4
    A = np.zeros((n, n))
    # Raff 
    rff = arr
    for i in range(len(rff)-1):
        first_ind = catpun(rff[i])
        second_ind = catpun(rff[i+1])
        A[first_ind, second_ind] += 1
        
    # Convert it into probablity the required math analysis is in my notebook
    row_sums = A.sum(axis=1, keepdims=True)
    normalized_A = A / row_sums
    rnd_A = np.round(normalized_A, decimals=2)
#     print(f'Matrix A = \n{rnd_A}')
    
    # Transpose of the matrix
    AT = rnd_A.T
    
    # Identity matrix
    identity_matrix = np.eye(n)

    # Subtract identity matrix from the transposed matrix
    ATI = AT - identity_matrix
    
    return ATI

def PuncRank(matrix):
    '''
    Returns the stationary matrix for a given Sentence length Array.
    '''
    # Create a new matrix with the last column replaced
    new_column = np.array([1, 1, 1, 1])
    modified_matrix = matrix.copy()
    modified_matrix[-1] = new_column
    #print(modified_matrix)
    
    # Right-hand side vector of the given equations
    b = np.array([0, 0, 0, 1])
    # Solve the system of equation now
    solution = np.linalg.solve(modified_matrix, b)
    solution = np.round(solution, decimals=2)
    
    return solution


def Punc_showA(arr):
    '''
    Converts an array ready to be solved using Linear Algebra
    '''
    # Initialize a nxn array with zeros
    n = 4
    A = np.zeros((n, n))
    # Raff 
    rff = arr
    for i in range(len(rff)-1):
        first_ind = catpun(rff[i])
        second_ind = catpun(rff[i+1])
        A[first_ind, second_ind] += 1
        
    # Convert it into probablity the required math analysis is in my notebook
    row_sums = A.sum(axis=1, keepdims=True)
    normalized_A = A / row_sums
    rnd_A = np.round(normalized_A, decimals=2)
#     print(f'Matrix A = \n{rnd_A}')
    return rnd_A

In [178]:
def create_punc_array(path):
    '''
    Chill 2
    '''
    paths = []
    for dirname, _, filenames in os.walk(path):
        for filename in filenames:
            paths.append(os.path.join(dirname, filename))

    puncarr = read_stories_forPunc(paths)
    return puncarr

pncarr1 = create_punc_array('/kaggle/input/bookscollection/Feluda all copy')
pncarr2 = create_punc_array('/kaggle/input/bookscollection/Rabindranath_Novels_all')
pncarr3 = create_punc_array('/kaggle/input/bookscollection/Himu_all')
pncarr4 = create_punc_array('/kaggle/input/bookscollection/Misir_Ali_all')

In [179]:
len(pncarr1), len(pncarr2), len(pncarr3)

(35, 13, 21)

In [180]:
pn_matArr1 = []
for i in range(len(pncarr1)):
    pn_matArr1.append(PuncRank(igenmatrix_Punc(pncarr1[i])))
pn_matArr2 = []
for i in range(len(pncarr2)):
    pn_matArr2.append(PuncRank(igenmatrix_Punc(pncarr2[i])))
pn_matArr3 = []
for i in range(len(pncarr3)):
    pn_matArr3.append(PuncRank(igenmatrix_Punc(pncarr3[i])))

In [181]:
pn_matArr2

[array([0.5 , 0.06, 0.02, 0.42]),
 array([0.49, 0.04, 0.03, 0.43]),
 array([0.47, 0.06, 0.02, 0.44]),
 array([0.52, 0.02, 0.01, 0.45]),
 array([0.49, 0.02, 0.02, 0.47]),
 array([0.53, 0.09, 0.07, 0.31]),
 array([0.56, 0.03, 0.02, 0.39]),
 array([0.52, 0.05, 0.03, 0.4 ]),
 array([0.53, 0.08, 0.03, 0.37]),
 array([0.45, 0.06, 0.03, 0.46]),
 array([0.44, 0.07, 0.02, 0.47]),
 array([0.48, 0.06, 0.04, 0.42]),
 array([0.56, 0.02, 0.02, 0.41])]

In [182]:
# Create a DataFrame with two columns
resdf = pd.DataFrame({'Writter 1': pn_matArr1[:13], 'Writter 2': pn_matArr2, 'Writer 3': pn_matArr3[:13]})
resdf

Writter 1                 Writter 2  \
0   [0.56, 0.11, 0.04, 0.29]   [0.5, 0.06, 0.02, 0.42]   
1   [0.55, 0.12, 0.04, 0.29]  [0.49, 0.04, 0.03, 0.43]   
2   [0.55, 0.09, 0.03, 0.33]  [0.47, 0.06, 0.02, 0.44]   
3    [0.6, 0.11, 0.02, 0.27]  [0.52, 0.02, 0.01, 0.45]   
4   [0.57, 0.09, 0.03, 0.31]  [0.49, 0.02, 0.02, 0.47]   
5   [0.59, 0.11, 0.03, 0.28]  [0.53, 0.09, 0.07, 0.31]   
6    [0.62, 0.1, 0.03, 0.26]  [0.56, 0.03, 0.02, 0.39]   
7   [0.53, 0.13, 0.03, 0.31]   [0.52, 0.05, 0.03, 0.4]   
8   [0.59, 0.11, 0.02, 0.28]  [0.53, 0.08, 0.03, 0.37]   
9   [0.63, 0.12, 0.02, 0.22]  [0.45, 0.06, 0.03, 0.46]   
10  [0.59, 0.11, 0.02, 0.28]  [0.44, 0.07, 0.02, 0.47]   
11  [0.55, 0.13, 0.03, 0.28]  [0.48, 0.06, 0.04, 0.42]   
12  [0.53, 0.14, 0.03, 0.31]  [0.56, 0.02, 0.02, 0.41]   

                    Writer 3  
0   [0.75, 0.13, 0.01, 0.11]  
1     [0.7, 0.13, 0.0, 0.17]  
2   [0.67, 0.13, 0.02, 0.17]  
3   [0.76, 0.14, 0.01, 0.09]  
4    [0.73, 0.13, 0.0, 0.14]  
5    [0.74, 0.11, 0.0, 0.15]  
6   [0.68, 0.13, 0.01, 0.18]  
7   [0.66, 0.13, 0.02, 0.19]  
8   [0.69, 0.11, 0.03, 0.17]  
9   [0.65, 0.15, 0.02, 0.18]  
10  [0.72, 0.14, 0.01, 0.13]  
11   [0.7, 0.13, 0.02, 0.15]  
12  [0.66, 0.14, 0.02, 0.18]

In [183]:
print(f'Writter 1 --> {calculate_avg(pn_matArr1)}')
print(f'Writter 2 --> {calculate_avg(pn_matArr2)}')
print(f'Writer 3 --> {calculate_avg(pn_matArr3)}')

Writter 1 --> [0.581 0.107 0.027 0.284]
Writter 2 --> [0.503 0.051 0.028 0.418]
Writer 3 --> [0.695 0.129 0.014 0.162]


<div style="text-align: center; background-color: lightblue;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h3> Create DataFrame For Punctuations Now</h3>
</div>

In [200]:
def add_punc_features(array, data):
    '''
    Bismillah
    '''
    states = 4
    # This is the stationary state
    st_state = []
    for i in range(len(array)):
        st_state.append(PuncRank(igenmatrix_Punc(array[i])))
        
    state_mat1 = []
    for i in range(len(array)):
        state_mat1.append(Punc_showA(array[i]))

    # Add stationary states in the dataframe
    for s in range(states):
        data[f'st_state{states}_{s+1}'] = np.array(st_state)[:, s]
    for s in range(states):
        for k in range(states):
            data[f'state{states}_{states*s+k+1}'] = np.array(state_mat1)[:, s, k]
        
            

In [201]:
psrdata = ({})
add_punc_features(pncarr1, psrdata)
psrdata = pd.DataFrame(psrdata)
print(psrdata.shape)
psrdata.head(2)

(35, 20)


st_state4_1  st_state4_2  st_state4_3  st_state4_4  state4_1  state4_2  \
0         0.56         0.11         0.04         0.29      0.52      0.13   
1         0.55         0.12         0.04         0.29      0.53      0.14   

   state4_3  state4_4  state4_5  state4_6  state4_7  state4_8  state4_9  \
0      0.03      0.32      0.52      0.11      0.03      0.34      0.55   
1      0.03      0.31      0.64      0.07      0.06      0.23      0.35   

   state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.08       0.13       0.24       0.66       0.09       0.04       0.22  
1       0.19       0.16       0.30       0.59       0.10       0.03       0.27

In [202]:
prtdata = ({})
add_punc_features(pncarr2, prtdata)
prtdata = pd.DataFrame(prtdata)
print(prtdata.shape)
prtdata.head(2)

(13, 20)


st_state4_1  st_state4_2  st_state4_3  st_state4_4  state4_1  state4_2  \
0         0.50         0.06         0.02         0.42      0.47      0.04   
1         0.49         0.04         0.03         0.43      0.44      0.02   

   state4_3  state4_4  state4_5  state4_6  state4_7  state4_8  state4_9  \
0      0.01      0.48      0.41      0.13      0.02      0.45      0.38   
1      0.02      0.52      0.28      0.10      0.03      0.59      0.47   

   state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.15       0.10       0.36       0.55       0.08       0.02       0.34  
1       0.06       0.13       0.34       0.58       0.06       0.04       0.32

In [203]:
phadata = ({})
add_punc_features(pncarr3, phadata)
phadata = pd.DataFrame(phadata)
print(phadata.shape)
phadata.head(2)

(21, 20)


st_state4_1  st_state4_2  st_state4_3  st_state4_4  state4_1  state4_2  \
0         0.75         0.13         0.01         0.11      0.76      0.12   
1         0.70         0.13         0.00         0.17      0.71      0.11   

   state4_3  state4_4  state4_5  state4_6  state4_7  state4_8  state4_9  \
0      0.01      0.11      0.72      0.13      0.01      0.14      0.69   
1      0.00      0.18      0.66      0.18      0.00      0.15      0.42   

   state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.16       0.03       0.12       0.71       0.20       0.01       0.08  
1       0.19       0.08       0.31       0.69       0.19       0.01       0.12

In [204]:
pmadata = ({})
add_punc_features(pncarr4, pmadata)
pmadata = pd.DataFrame(pmadata)
print(pmadata.shape)
pmadata.head(2)

(21, 20)


st_state4_1  st_state4_2  st_state4_3  st_state4_4  state4_1  state4_2  \
0         0.76         0.12         0.02         0.10      0.78      0.11   
1         0.72         0.10         0.01         0.17      0.74      0.08   

   state4_3  state4_4  state4_5  state4_6  state4_7  state4_8  state4_9  \
0      0.02      0.09      0.73      0.14      0.01      0.12      0.66   
1      0.01      0.18      0.58      0.07      0.01      0.34      0.79   

   state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.22       0.06       0.06       0.66        0.2       0.01       0.14  
1       0.09       0.02       0.09       0.70        0.2       0.02       0.08

## Merge them

In [206]:
Punc_showA(pncarr3[0])

array([[0.76, 0.12, 0.01, 0.11],
       [0.72, 0.13, 0.01, 0.14],
       [0.69, 0.16, 0.03, 0.12],
       [0.71, 0.2 , 0.01, 0.08]])

In [185]:
# pn_matArr1 = []
# for i in range(len(pncarr1)):
#     pn_matArr1.append(PuncRank(igenmatrix_Punc(pncarr1[i])))
    
# state_mat1 = []
# for i in range(len(pncarr1)):
#     state_mat1.append(Punc_showA(pncarr1[i]))

# psrdata = pd.DataFrame(
# {
#     'punc_state_mat' : state_mat1,
#     'punc_st_state': pn_matArr1,
# })

# print(psrdata.shape)

(35, 2)


In [186]:
# pn_matArr1 = []
# for i in range(len(pncarr2)):
#     pn_matArr1.append(PuncRank(igenmatrix_Punc(pncarr2[i])))
    
# state_mat1 = []
# for i in range(len(pncarr2)):
#     state_mat1.append(Punc_showA(pncarr2[i]))

# prtdata = pd.DataFrame(
# {
#     'punc_state_mat' : state_mat1,
#     'punc_st_state': pn_matArr1,
# })

# print(prtdata.shape)

(13, 2)


In [187]:
# pn_matArr1 = []
# for i in range(len(pncarr3)):
#     pn_matArr1.append(PuncRank(igenmatrix_Punc(pncarr3[i])))
    
# state_mat1 = []
# for i in range(len(pncarr3)):
#     state_mat1.append(Punc_showA(pncarr3[i]))

# phadata = pd.DataFrame(
# {
#     'punc_state_mat' : state_mat1,
#     'punc_st_state': pn_matArr1,
# })

# print(phadata.shape)

(21, 2)


In [205]:
# pn_matArr1 = []
# for i in range(len(pncarr4)):
#     pn_matArr1.append(PuncRank(igenmatrix_Punc(pncarr4[i])))
    
# state_mat1 = []
# for i in range(len(pncarr4)):
#     state_mat1.append(Punc_showA(pncarr4[i]))

# pmadata = pd.DataFrame(
# {
#     'punc_state_mat' : state_mat1,
#     'punc_st_state': pn_matArr1,
# })

# print(phadata.shape)

In [217]:
pdata = pd.concat([psrdata, prtdata, phadata, pmadata], axis=0)
pdata.shape

(90, 20)

<div style="text-align: center; background-color: lightblue;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h2> MAKE THE FINAL DATAFRAME </h2>
</div>

In [212]:
data = data.reset_index(drop=True)
data.head(2)

book_id        writer  st_state5_dif3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray          0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          0.261259   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.253602          0.207741          0.138053          0.182240   
1          0.261148          0.217963          0.113027          0.146602   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state10_dif2_96  \
0       0.332685       0.282101       0.177043  ...         0.078014   
1       0.340206       0.283505       0.185567  ...         0.054054   

   state10_dif2_97  state10_dif2_98  state10_dif2_99  state10_dif2_100  \
0         0.092199         0.056738         0.035461          0.092199   
1         0.135135         0.027027         0.054054          0.135135   

       mean  median  mode   variance   std_dev  
0  8.076395     7.0     5  31.971834  5.654364  
1  7.318498     6.0     3  27.927666  5.284663  

[2 rows x 465 columns]

In [218]:
pdata = pdata.reset_index(drop=True)
pdata.head(2)

st_state4_1  st_state4_2  st_state4_3  st_state4_4  state4_1  state4_2  \
0         0.56         0.11         0.04         0.29      0.52      0.13   
1         0.55         0.12         0.04         0.29      0.53      0.14   

   state4_3  state4_4  state4_5  state4_6  state4_7  state4_8  state4_9  \
0      0.03      0.32      0.52      0.11      0.03      0.34      0.55   
1      0.03      0.31      0.64      0.07      0.06      0.23      0.35   

   state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.08       0.13       0.24       0.66       0.09       0.04       0.22  
1       0.19       0.16       0.30       0.59       0.10       0.03       0.27

In [219]:
pdata.shape, data.shape

((90, 20), (90, 465))

In [220]:
maindata = pd.concat([data, pdata], axis = 1)
maindata.shape

(90, 485)

In [221]:
maindata.head()

book_id        writer  st_state5_dif3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray          0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          0.261259   
2             feluda_13_Bombayer_Bombete  Satyajit Ray          0.161039   
3          feluda_12_Ghurghutiar_Ghotona  Satyajit Ray          0.176471   
4        feluda_19_JotoKando_Kathmandute  Satyajit Ray          0.206256   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.253602          0.207741          0.138053          0.182240   
1          0.261148          0.217963          0.113027          0.146602   
2          0.231818          0.218831          0.153247          0.235065   
3          0.255962          0.228935          0.131955          0.206677   
4          0.221408          0.204301          0.132454          0.235582   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state4_7  state4_8  \
0       0.332685       0.282101       0.177043  ...      0.03      0.34   
1       0.340206       0.283505       0.185567  ...      0.06      0.23   
2       0.286290       0.298387       0.161290  ...      0.04      0.33   
3       0.270270       0.315315       0.180180  ...      0.03      0.30   
4       0.312796       0.236967       0.199052  ...      0.03      0.22   

   state4_9  state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  \
0      0.55       0.08       0.13       0.24       0.66       0.09       0.04   
1      0.35       0.19       0.16       0.30       0.59       0.10       0.03   
2      0.54       0.09       0.09       0.29       0.63       0.09       0.02   
3      0.72       0.00       0.06       0.22       0.62       0.09       0.02   
4      0.55       0.08       0.09       0.28       0.59       0.07       0.03   

   state4_16  
0       0.22  
1       0.27  
2       0.26  
3       0.26  
4       0.31  

[5 rows x 485 columns]

In [222]:
maindata.to_excel('author_data.xlsx', index=False)

In [223]:
df = pd.read_excel('/kaggle/working/author_data.xlsx')
df.head()

book_id        writer  st_state5_dif3_1  \
0               feluda_33_Noyon_Rahashya  Satyajit Ray          0.218364   
1  feluda_22_OmborSen_Ontordhan_Rahashya  Satyajit Ray          0.261259   
2             feluda_13_Bombayer_Bombete  Satyajit Ray          0.161039   
3          feluda_12_Ghurghutiar_Ghotona  Satyajit Ray          0.176471   
4        feluda_19_JotoKando_Kathmandute  Satyajit Ray          0.206256   

   st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  st_state5_dif3_5  \
0          0.253602          0.207741          0.138053          0.182240   
1          0.261148          0.217963          0.113027          0.146602   
2          0.231818          0.218831          0.153247          0.235065   
3          0.255962          0.228935          0.131955          0.206677   
4          0.221408          0.204301          0.132454          0.235582   

   state5_dif3_1  state5_dif3_2  state5_dif3_3  ...  state4_7  state4_8  \
0       0.332685       0.282101       0.177043  ...      0.03      0.34   
1       0.340206       0.283505       0.185567  ...      0.06      0.23   
2       0.286290       0.298387       0.161290  ...      0.04      0.33   
3       0.270270       0.315315       0.180180  ...      0.03      0.30   
4       0.312796       0.236967       0.199052  ...      0.03      0.22   

   state4_9  state4_10  state4_11  state4_12  state4_13  state4_14  state4_15  \
0      0.55       0.08       0.13       0.24       0.66       0.09       0.04   
1      0.35       0.19       0.16       0.30       0.59       0.10       0.03   
2      0.54       0.09       0.09       0.29       0.63       0.09       0.02   
3      0.72       0.00       0.06       0.22       0.62       0.09       0.02   
4      0.55       0.08       0.09       0.28       0.59       0.07       0.03   

   state4_16  
0       0.22  
1       0.27  
2       0.26  
3       0.26  
4       0.31  

[5 rows x 485 columns]

In [224]:
maindata.dtypes

book_id              object
writer               object
st_state5_dif3_1    float64
st_state5_dif3_2    float64
st_state5_dif3_3    float64
                     ...   
state4_12           float64
state4_13           float64
state4_14           float64
state4_15           float64
state4_16           float64
Length: 485, dtype: object

In [226]:
# df['st_state5x3'] = df['st_state5x3'].to_list()

In [227]:
# type(df['st_state5x3']), type(maindata['st_state5x3'])

In [ ]:
maindata = data

In [228]:
from sklearn.preprocessing import LabelEncoder
# Initialize LabelEncoder
label_encoder = LabelEncoder()
maindata['en_writer'] = label_encoder.fit_transform(maindata['writer'])

In [229]:
maindata['en_writer'].value_counts()

en_writer
0    42
2    35
1    13
Name: count, dtype: int64

In [230]:
maindata = maindata.reset_index(drop=True)
maindata['book_id'][40]

'ProjapotirNirbondho1908'

In [231]:
maindata = maindata[maindata['book_id'] != 'ProjapotirNirbondho1908']

In [232]:
maindata.columns

Index(['book_id', 'writer', 'st_state5_dif3_1', 'st_state5_dif3_2',
       'st_state5_dif3_3', 'st_state5_dif3_4', 'st_state5_dif3_5',
       'state5_dif3_1', 'state5_dif3_2', 'state5_dif3_3',
       ...
       'state4_8', 'state4_9', 'state4_10', 'state4_11', 'state4_12',
       'state4_13', 'state4_14', 'state4_15', 'state4_16', 'en_writer'],
      dtype='object', length=486)

In [233]:
X = maindata.drop(['book_id', 'writer', 'en_writer', 'median', 'mode', 'variance', 'std_dev', 'mean'], axis=1)
y = maindata['en_writer']

In [234]:
X.head(2)

st_state5_dif3_1  st_state5_dif3_2  st_state5_dif3_3  st_state5_dif3_4  \
0          0.218364          0.253602          0.207741          0.138053   
1          0.261259          0.261148          0.217963          0.113027   

   st_state5_dif3_5  state5_dif3_1  state5_dif3_2  state5_dif3_3  \
0          0.182240       0.332685       0.282101       0.177043   
1          0.146602       0.340206       0.283505       0.185567   

   state5_dif3_4  state5_dif3_5  ...  state4_7  state4_8  state4_9  state4_10  \
0       0.091440       0.116732  ...      0.03      0.34      0.55       0.08   
1       0.092784       0.097938  ...      0.06      0.23      0.35       0.19   

   state4_11  state4_12  state4_13  state4_14  state4_15  state4_16  
0       0.13       0.24       0.66       0.09       0.04       0.22  
1       0.16       0.30       0.59       0.10       0.03       0.27  

[2 rows x 478 columns]

In [235]:
y.head(3)

0    2
1    2
2    2
Name: en_writer, dtype: int64

In [236]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# np
# Print the lengths of the sets
print("Training set size:", len(X_train))
print("Test set size:", len(X_test))

Training set size: 71
Test set size: 18


In [237]:
y_train.value_counts(), y_test.value_counts()

(en_writer
 0    35
 2    27
 1     9
 Name: count, dtype: int64,
 en_writer
 2    8
 0    7
 1    3
 Name: count, dtype: int64)

In [238]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [239]:
# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

In [240]:
y_pred, np.array(y_test)

(array([1, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 0]),
 array([1, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 1, 0, 0, 1, 0, 0]))

In [241]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [242]:
# Print the results
print("Accuracy:", accuracy)
print("\nClassification Report:\n", report)

Accuracy: 0.9444444444444444

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      0.67      0.80         3
           2       0.89      1.00      0.94         8

    accuracy                           0.94        18
   macro avg       0.96      0.89      0.91        18
weighted avg       0.95      0.94      0.94        18



<div style="text-align: center; background-color: lightblue;padding: 15px; border-radius: 5px; margin-bottom: 10px;">
    <h2> Now Plot the Corelation Graph of the matrix </h2>
</div>

In [244]:
# df = pd.read_excel('/kaggle/input/author-data/dataa.xlsx')
# df.dtypes

In [245]:
# type(df['st_state5x3'][0])

In [247]:
# pip install h5py

In [248]:
# # Save to HDF5
# maindata.to_hdf('output.h5', key='my_data', mode='w')

# # Read from HDF5
# loaded_df = pd.read_hdf('output.h5', key='my_data')

# # Display the loaded DataFram
# loaded_df.head(2)

In [249]:
# loaded_df['state_mat4x4'][0]

In [250]:
# loaded_df.dtypes